//
// Generated file, do not edit! Created by opp_msgtool 6.1 from DVMessage.msg.
//

#ifndef __DVMESSAGE_M_H
#define __DVMESSAGE_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0601
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif

struct RoutingEntry;
class DVMessage;
/**
 * Struct generated from DVMessage.msg:15 by opp_msgtool.
 */
struct RoutingEntry
{
    RoutingEntry();
    int destinationNode = 0;
    double cost = 0;
};

// helpers for local use
void __doPacking(omnetpp::cCommBuffer *b, const RoutingEntry& a);
void __doUnpacking(omnetpp::cCommBuffer *b, RoutingEntry& a);

inline void doParsimPacking(omnetpp::cCommBuffer *b, const RoutingEntry& obj) { __doPacking(b, obj); }
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, RoutingEntry& obj) { __doUnpacking(b, obj); }

/**
 * Class generated from <tt>DVMessage.msg:20</tt> by opp_msgtool.
 * <pre>
 * message DVMessage
 * {
 *     RoutingEntry distanceVector[];
 * }
 * </pre>
 */
class DVMessage : public ::omnetpp::cMessage
{
  protected:
    RoutingEntry *distanceVector = nullptr;
    size_t distanceVector_arraysize = 0;

  private:
    void copy(const DVMessage& other);

  protected:
    bool operator==(const DVMessage&) = delete;

  public:
    DVMessage(const char *name=nullptr, short kind=0);
    DVMessage(const DVMessage& other);
    virtual ~DVMessage();
    DVMessage& operator=(const DVMessage& other);
    virtual DVMessage *dup() const override {return new DVMessage(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual void setDistanceVectorArraySize(size_t size);
    virtual size_t getDistanceVectorArraySize() const;
    virtual const RoutingEntry& getDistanceVector(size_t k) const;
    virtual RoutingEntry& getDistanceVectorForUpdate(size_t k) { return const_cast<RoutingEntry&>(const_cast<DVMessage*>(this)->getDistanceVector(k));}
    virtual void setDistanceVector(size_t k, const RoutingEntry& distanceVector);
    virtual void insertDistanceVector(size_t k, const RoutingEntry& distanceVector);
    [[deprecated]] void insertDistanceVector(const RoutingEntry& distanceVector) {appendDistanceVector(distanceVector);}
    virtual void appendDistanceVector(const RoutingEntry& distanceVector);
    virtual void eraseDistanceVector(size_t k);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const DVMessage& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, DVMessage& obj) {obj.parsimUnpack(b);}


namespace omnetpp {

inline any_ptr toAnyPtr(const RoutingEntry *p) {return any_ptr(p);}
template<> inline RoutingEntry *fromAnyPtr(any_ptr ptr) { return ptr.get<RoutingEntry>(); }
template<> inline DVMessage *fromAnyPtr(any_ptr ptr) { return check_and_cast<DVMessage*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __DVMESSAGE_M_H

